[tools]
delta = "0.19.2"
fd = "10.4.2"
fzf = "0.71.0"
helix = "25.07.1"
just = "1.49.0"
neovim = "0.12.1"
rg = "15.1.0"
zellij = "0.44.1"

[tasks.helix-init]
description = "install extra dependecies for helix"
run = "python3 -mpip install --user 'python-lsp-server[all]'"

[tasks.nvim-init]
description = "install extra dependecies for neovim"
run = "python3 -mpip install --user neovim"
