[tools]
bat = "0.26.1"
delta = "0.19.2"
"cargo:dufs" = "0.46.0"
dust = "1.2.5"
fd = "10.5.0"
fzf = "0.74.3"
helix = "25.07.1"
just = "1.58.0"
neovim = "0.12.5"
"aqua:dalance/procs" = "0.14.12"
rg = "15.2.0"
tokei = "14.0.0"
yazi = "26.8.15"
zellij = "0.45.1"

[tasks.helix-init]
description = "install extra dependecies for helix"
run = "python3 -mpip install --user 'python-lsp-server[all]'"

[tasks.nvim-init]
description = "install extra dependecies for neovim"
run = "python3 -mpip install --user neovim"

[tasks.setup]
description = "install configured editor dependencies"
depends = ["helix-init", "nvim-init"]
