theme = "onedark"

[editor]
auto-save = true
true-color = true
cursorline = true
cursorcolumn = true
color-modes = true
bufferline = "multiple"
line-number = "relative"
rulers = [80, 120]
text-width = 120

[editor.soft-wrap]
enable = true
#max-wrap = 25 # increase value to reduce forced mid-word wrapping
#max-indent-retain = 0
#wrap-indicator = "↪"  # set wrap-indicator to "" to hide it

[editor.whitespace.render]
nbsp = "all"
tab = "all"
#newline = "all"
[editor.whitespace.characters]
nbsp = "⍽"
#newline = "⏎"
#newline = "¬"
#space = "·"
tab = "▸" # "→"
tabpad = " " #"·" # Tabs will look like "→···" (depending on tab width)

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 0

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "version-control", "selections", "position", "file-encoding", "file-line-ending", "file-type"]

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = true

[keys.normal]
# select the whole word under cursor
"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection"]
# dd -> xd
#d = { d = ["extend_line_below", "delete_selection"] }

[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"
x = ":toggle whitespace.render all none"
# zen mode
z = ":toggle gutters.line-numbers.min-width 48 3"
o = ":pipe-to wezterm cli split-pane -- helix-live-grep"
l = ":pipe-to helix-debug-print"
e = ":sh zellij run -f -x 10% -y 10% --width 80% --height 80% -- helix-yazi"

# https://github.com/helix-editor/helix/discussions/8000#discussioncomment-6821291
# [keys.normal.space.g]
# g = ":sh zellij action new-tab -l lg"
# s = ":sh zellij run -fc -- lazygit"

# https://github.com/quantonganh/helix-wezterm/tree/main
# [keys.normal.";"]
# b = ":sh helix-wezterm blame"
# c = ":sh helix-wezterm check"
# e = ":sh helix-wezterm explorer"
# f = ":sh helix-wezterm fzf"
# g = ":sh helix-wezterm lazygit"
# o = ":sh helix-wezterm open"
# r = ":sh helix-wezterm run"
# s = ":sh helix-wezterm test_single"
# t = ":sh helix-wezterm test_all"

# https://github.com/davxy/dotfiles/blob/main/helix/config.toml
# Add some custom bindings to the space-space menu (custom)
[keys.normal.'space'.'space']
# Extensions using custom script
c = ":pipe-to helix-ext cd --current"
# Interactive search in current working directory
s = ":pipe-to helix-ext search --current"
# Interactive search in current working directory (include path name in the search)
S = ":pipe-to helix-ext search --current-inc-path"
# Interactive search in current git directory
w = ":pipe-to helix-ext search --workspace"
# Interactive search in current git directory (include path name in the search)
W = ":pipe-to helix-ext search --workspace-inc-path"
# Interactive search in current buffer
b = ":pipe-to helix-ext search --buffer"
# Git-ui
g = ":pipe-to helix-ext git --ui"
# Git status
m = ":pipe-to helix-ext git --status"
# Git blame
B = ":pipe-to helix-ext git --blame"
# Git browse github repo using default browser
O = ":pipe-to helix-ext git --browse"
# Markdown toc
i = ":pipe-to helix-ext markdown --toc"
# Diff current buffer with content on disk
d = ":pipe-to helix-ext diff"
# Files tree
t = ":pipe-to helix-ext tree"
# Terminal
T = ":pipe-to helix-ext term"
# Cleanup helix-ext data
C = ":pipe-to helix-ext clean"
