theme = "onedark"

[editor]
auto-save = true
true-color = true
cursorline = true
cursorcolumn = true
color-modes = true
bufferline = "multiple"
line-number = "relative"
rulers = [80, 120]
text-width = 120

[editor.soft-wrap]
enable = true
#max-wrap = 25 # increase value to reduce forced mid-word wrapping
#max-indent-retain = 0
#wrap-indicator = "↪"  # set wrap-indicator to "" to hide it

[editor.whitespace.render]
nbsp = "all"
tab = "all"
[editor.whitespace.characters]
nbsp = "⍽"
#newline = "⏎"
#newline = "¬"
#space = "·"
tab = "▸" # "→"
tabpad = " " #"·" # Tabs will look like "→···" (depending on tab width)

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 0

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "version-control", "selections", "position", "file-encoding", "file-line-ending", "file-type"]

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = true

[keys.normal.space]
o = ":pipe-to wezterm cli split-pane -- helix-live-grep"
l = ":pipe-to helix-debug-print"