# [[language]]
# name = "cpp"
# language-server = { command = "clangd", args = [
#     # for performance
#     "-j=8",
#     "--malloc-trim",
#     "--pch-storage=memory",
#     "--background-index",
#     # "--compile-commands-dir=${workspaceFolder}",
#     "--inlay-hints",
#     "--completion-style=detailed",
#     # --header-insertion=<value>      - Add #include directives when accepting code completions
#     #  =iwyu                          -   Include what you use. Insert the owning header for top-level symbols, unless the header is already directly included or the symbol is forward-declared
#     #  =never                         -   Never insert #include directives as part of code completion
#     "--header-insertion=never",
#     # Prepend a circular dot or space before the completion label, depending on whether an include line will be inserted or not
#     "--header-insertion-decorators",
#     # When disabled, completions contain only parentheses for function calls. When enabled, completions also contain placeholders for method parameters
#     "--function-arg-placeholders",
# ] }

[[language]]
name = "python"
# language-servers = [ "pylsp", "ruff" ]
language-servers = [ "pylsp" ]
auto-format = true

# pip install black
[language.formatter]
command = "black"
args = ["--line-length=120", "--quiet", "-"]

# https://github.com/helix-editor/helix/wiki/Language-Server-Configurations#python---pylsp
# python-lsp-ruff is a 3rd party plugin
# pip install python-lsp-server[rope] python-lsp-ruff
[language-server.pylsp.config.pylsp.plugins]
flake8 = {enabled = false}
pylint = {enabled = false}
autopep8 = {enabled = false}
mccabe = {enabled = false}
pycodestyle = {enabled = false}
pyflakes = {enabled = false}
yapf = {enabled = false}
[language-server.pylsp.config.pylsp.plugins.ruff]
# ruff will disable pycodestyle, pyflakes, mccabe, autopep8, and yapf by default, unless they are explicitly enabled
enabled = true
ignore = ["E402"]
formatEnabled = true
lineLength = 88

# pyright need nodejs v12+
# [language-server.pyright]
# command = "pyright-langserver"
# args = ["--stdio"]
# [language-server.pyright.config]
# reportMissingTypeStubs = false
# [language-server.pyright.config.python.analysis]
# typeCheckingMode = "basic"
# autoImportCompletions = true

# https://github.com/helix-editor/helix/wiki/Language-Server-Configurations#python---ruff
# pip install ruff-lsp
# [language-server.ruff]
# command = "ruff-lsp"
# [language-server.ruff.config.settings]
# args = []
# # args = ["--ignore", "E501"]
