return {
	-- {
	--   "numToStr/Comment.nvim",
	--   dependencies = { "JoosepAlviste/nvim-ts-context-commentstring" },
	--   opts = function()
	--     local U = require("Comment.utils")
	--     return {
	--       pre_hook = require("ts_context_commentstring.integrations.comment_nvim").create_pre_hook(),
	--       post_hook = function(ctx)
	--         -- Check whether we were in VISUAL mode
	--         if ctx.cmotion == U.cmotion.v or ctx.cmotion == U.cmotion.V then
	--           vim.cmd("norm! gv")
	--         end
	--       end,
	--     }
	--   end,
	-- },
	-- { "JoosepAlviste/nvim-ts-context-commentstring", lazy = true },
	-- {
	--   "echasnovski/mini.comment",
	--   dependencies = { "JoosepAlviste/nvim-ts-context-commentstring", lazy = true },
	--   event = "VeryLazy",
	--   opts = {
	--     hooks = {
	--       pre = function()
	--         require("ts_context_commentstring.internal").update_commentstring({})
	--       end,
	--     },
	--   },
	--   config = function(_, opts)
	--     require("mini.comment").setup(opts)
	--   end,
	-- },
}
