#!/usr/bin/env -S just --justfile
# ^ A shebang isn't required, but allows a justfile to be executed
#   like a script, with `./justfile test`, for example.

# alias b := build

default:
    @just --justfile {{justfile()}} --list

hello NAME:
    @echo "Hello, {{NAME}}"
