version: "3"

services:
  workspace:
    env_file: .env
    environment:
      - http_proxy=${localEnv:http_proxy}
      - https_proxy=${localEnv:https_proxy}
      - no_proxy=${localEnv:no_proxy}
      - DISPLAY=${localEnv:DISPLAY}
    build:
      context: ../ci/docker
      dockerfile: Dockerfile
      args:
        - HttpsProxyHost=${localEnv:HTTP_PROXY_HOST}
        - HttpsProxyPort=${localEnv:HTTP_PROXY_PORT}
        - HttpProxyHost=${localEnv:HTTP_PROXY_HOST}
        - HttpProxyPort=${localEnv:HTTP_PROXY_PORT}
    volumes:
      - ${localEnv:HOME}/.gitconfig:/home/vscode/.gitconfig,
      - ${localEnv:HOME}/.ssh:/home/vscode/.ssh,
      # - ${localEnv:HOME}/.Xauthority:/home/vscode/.Xauthority,
      - ${localWorkspaceFolder}/.devcontainer/sbt/repositories:/home/vscode/.sbt/repositories,
      - ${localEnv:STORAGE}:/storage,
    network_mode: host
    privileged: true
    # ports:
    #   - "80:80"
    #   - "443:443"
    init: true
    restart: unless-stopped

# networks:
#   '1':
#     driver: host

# volumes:
#   '1':
#     name: '23'
#     driver: local
